### ISSUE TITLE
Feature: global/user configuration

### ISSUE THREAD

**Issue by trasherdk** [p42ai/refactor-vscode#10]
While I really enjoy this extension, the inability to disable something like `Add Numeric Separator` without polluting upstream repositories with my personal preferences, kinda annoy me.

Being able to configure stuff like that in VS Code User settings would help.

On a side note: As per [p42 configuration](https://p42.ai/documentation/p42-for-vscode/configuration) 

Adding a `p42.toml` to `.gitignore` and a `p42.toml` file to repository root, containing:
```
[refactoring.add-numeric-separator]
enable = false
```
Have zero effect ???
![image](https://user-images.githubusercontent.com/5003891/149606660-3355b922-0980-4cea-807a-c0b58254d21a.png)

**Comment by lgrammel** [comment]
Thanks for the feedback. 

The TOML configuration issue is a bug. I'll work on a fix today.

The VS Code settings are something I'm considering. However they can potentially conflict with the `p42.toml` configuration, which is why I haven't added them yet. In particular, cases where a user has multiple workspaces and the `p42.toml` (team/repository oconfiguration) sets certain refactorings `true` in one workspace and `false` in another, and the VS Code settings (user configuration) enables them in both (leading to issues in the workspace where they should be disabled). 

My current is that there could be an enum with 3 settings in the configuration for each refactoring with suggestions:
* "always show"
* "never show"
* "configured in p42.toml (default)"

Would that work for your use case?

**Comment by lgrammel** [comment]
I just looked deeper into the `p42.toml` configuration issue that you reported. While the configuration does not get immediately applied when you edit `p42.toml`, it does refresh once the file is edited or reloaded. As a work-around, you can just (with the refactoring being disabled in the `p42.toml`) add and remove a space in the file you are editing and the suggestions should update (in your case remove the hints for the numeric literals). Please let me know if that works for you. I'll implement a file watching mechanism for the `p42.toml` meanwhile.

**Comment by lgrammel** [comment]
@trasherdk I've just released version 1.68.2. It automatically updates the hints in open editors when `p42.toml` is saved. Please let me know if you still encounter the bug in version 1.68.2 or higher. Thanks again for the bug report!

**Comment by lgrammel** [comment]
@trasherdk I also noticed a small typo in your `p42.toml`: the setting is called `enabled` (not `enable`).

**Comment by trasherdk** [comment]
Damn.. That's embarrassing :blush: A typo in the config.
So, it turns out, I was the bug.

It looks like extensions are auto updating, as I'm already on `1.68.2` and with the fixed typo all is good.

I would still love to see config in user settings, avoiding that `p42.toml` file.

In the case where a project already has `p42.toml` config, that config should override users personal preferences.

**Comment by lgrammel** [comment]
It happens to the best of us 😊  ideally, the content of `p42.toml` would get validated, and there would be syntax errors while editing, but that's a pretty lousy effort/value ratio, thus not a priority.

Regarding the user settings, I like your approach of having the project config override the user preferences way better than my original idea. That way, projects could easily enforce their settings. I'll see if I can get this implemented by the end of Jan.

**Comment by trasherdk** [comment]
Thank you for a useful tool, and looking forward to that settings feature.

I'm closing this a resolved :+1:

**Comment by lgrammel** [comment]
@trasherdk I've added the VS Code settings in `1.72.0`. Here is a quick overview: https://twitter.com/p42ai/status/1484541693324111874

**Comment by trasherdk** [comment]
That is so cool :+1:  I just got the updated plug-in :smile:  
This is one of the more useful tools in the arsenal.
