### ISSUE TITLE
Issue with Push-Parameter_Into_IIFE

### ISSUE THREAD

**Issue by chandan192** [p42ai/refactor-vscode#12]
Hi @lgrammel ,

Please refer the below snaps for the issue.

Before refactoring
-------------------------
![image](https://user-images.githubusercontent.com/36302444/151746691-3d2aaceb-7a9e-42c6-9382-ab35a8eba6e8.png)

After refactoring
-------------------------
![image](https://user-images.githubusercontent.com/36302444/151746741-a5f6084f-d2ee-4ab8-af1f-3fb59b5a27cb.png)

check for the index variable` i` in forEach loop after refactoring.

**Comment by lgrammel** [comment]
Thanks for the bug report! I'll look into fixing this asap.

**Comment by lgrammel** [comment]
@chandan192 I just released version `1.78.1`, which fixes the bug. Please re-open this issue if you still encounter the bug `1.78.1` or higher. Thanks again for the bug report!
