### ISSUE TITLE
Convert to template string issue

### ISSUE THREAD

**Issue by ciruz** [p42ai/refactor-vscode#13]
Hey, 
I noticed a error when refactoring this code:

```javascript
fetch(
    process.env.API_URL +
      `/foo/bar?id=${id}&token=${token}`
  );
```

![image](https://user-images.githubusercontent.com/987947/153569006-c9c44370-0368-437b-936d-23edbb2acfcb.png)

Result:

```javascript
fetch(
    `${process.env.API_URL}/foo/bar?id=${id}&token=`token}`
  );
```

Best,
Tom

**Comment by lgrammel** [comment]
Hi Tom,

thanks for the bug report. This looks like a refactoring that comes with VS Code (built-in), not P42. P42 refactorings have a '[P42]' at the end of the action label in the context menu. If this is a P42 refactoring, please re-open the issue.

Best, Lars

**Comment by ciruz** [comment]
Oh, you are right, P42 does it right but vscode not.

**Comment by lgrammel** [comment]
Awesome, thanks for confirming!
