### ISSUE TITLE
Optional chaining conversion issue

### ISSUE THREAD

**Issue by verccety** [p42ai/refactor-vscode#16]
P42 tooltip  **(v1.101.1)**
>_You can shorten 'this.control && this.control.invalid && this.control.touched' expression with optional chaining.p42 [use-optional-chaining](https://p42.ai/documentation/code-action/use-optional-chaining)_

```js
  return this.control && this.control.invalid && this.control.touched;
```

P42 suggests incorrectly to convert into
 ```js   
return this.control?.invalid?.touched;
```

**Comment by lgrammel** [comment]
Thanks for the bug report! I'll update once I have a fix.

**Comment by lgrammel** [comment]
@verccety I've reworked the optional chaining refactoring in v1.103.0 and fixed the bug. Please re-open this issue if you still encounter the bug in v1.103 or higher. Thanks again for the bug report!
