### ISSUE TITLE
Only suggest "Move initialization into constructor" when on the `=` sign, not in the entire expression.

### ISSUE THREAD

**Issue by hediet** [p42ai/refactor-vscode#22]
![image](https://user-images.githubusercontent.com/2931520/171814848-596c71fa-8f3e-4ef3-a2f9-65fa97b9fe35.png)

**Comment by lgrammel** [comment]
Thanks for reporting! I'll probably keep the activation on the left side of the expression as well (`=` might be too small), so you could activate the refactoring on `this.aVariable = `, but not on the right hand side. Would that work for you?

**Comment by lgrammel** [comment]
I agree - the perfect activation ranges are still an open question to me. There is a tradeoff between the activation ranges not being available where you'd want/expect them, and refactorings showing up when they are clearly not intended at that position. 

Currently the default is the full AST match, but that quickly gets tricky in particular for nested functions. However, for e.g. the "move intialization" refactoring, when there are constants on the right hand side (e.g. `"some value"`), then activating on them might be nice, but it could lead to inconsistencies in the UX which can be confusing. 

I think it'll come down to a lot of experimentation and refinement before I can generalize, but maybe there is some general good way to do this that I just don't see yet.

For this particular case here, I ended up changing the activation range to the left hand side, the = and the first 3 characters of the right hand side, so it's readily availalbe but showing in unwanted places.

`v1.111.2` with the change should be available soon :) Thanks again
