### ISSUE TITLE
Refactoring Idea: new Array<T> to :T[] = [];

### ISSUE THREAD

**Issue by hediet** [p42ai/refactor-vscode#24]
```ts
const arr = new Array<T>();
```
<->
```ts
const arr: T[] = [];
```

The second one is faster (by 5-10%).

**Comment by lgrammel** [comment]
Thanks, great suggestion!

**Comment by lgrammel** [comment]
I've just released `v1.121.0`, which adds this refactoring. Thanks for the idea!

![action-convert-new-array-to-array-literal](https://user-images.githubusercontent.com/205036/177277209-2b62bffe-0b7f-4e8c-a8c7-ef4198576873.gif)
