### ISSUE TITLE
Inline Const Not Available

### ISSUE THREAD

**Issue by hediet** [p42ai/refactor-vscode#26]
![image](https://user-images.githubusercontent.com/2931520/173812249-72a0a322-0c29-4921-9e09-d8ff9ca4b52f.png)

**Comment by lgrammel** [comment]
Thanks for the bug report! This is most likely hard to reproduce without more context. Is there a larger code snippet (e.g. the whole function) that you could share?

**Comment by hediet** [comment]
I completely changed that function unfortunately.
