### ISSUE TITLE
Too Agressive Add {...} to arrow function

### ISSUE THREAD

**Issue by hediet** [p42ai/refactor-vscode#30]
![image](https://user-images.githubusercontent.com/2931520/175044493-250a77b0-177e-4191-ad2a-bc825be3e931.png)

**Comment by lgrammel** [comment]
Thanks for the bug report! 

I'm trying to understand what the bug is here. Add to arrow function should be availalbe, as it seems to be a legit code action, and it does not seem to be suggested. 

Are you looking for a better activation range? Or is it about the action showing up as a quick-fix?

**Comment by lgrammel** [comment]
That makes total sense. I'm thinking about having 2 levels of activation:
* quick fix on the function head and the arrow and the space after, i.e., on `() => ` here.
* code action (refactoring menu, convert menu) on the function it is now
Would this option work for you?

**Comment by lgrammel** [comment]
I've tweaked the activation ranges for 'add/remove {}' in `v1.120.2`. Thanks for the feedback!
