### ISSUE TITLE
UI is empty

### ISSUE THREAD

**Issue by Spongman** [p42ai/refactor-vscode#31]
![image](https://user-images.githubusercontent.com/1088194/175665177-b628d833-1906-4a18-b17e-b57c336eec2a.png)

the count changes when i open different .js files, but nothing shows in the UI.

**Comment by Spongman** [comment]
i see this in the vscode devtools console log:
```
notificationsAlerts.ts:42 Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..```

**Comment by lgrammel** [comment]
Thanks for the bug report!

The following information would help me reproduce the issue:

- What is your VS Code version?
- What is your P42 version?
- What environment are you using (github.dev/vscode.dev/VSCode app)?
- What operating system are you using?

**Comment by Spongman** [comment]
restarting vscode fixed it.

**Comment by lgrammel** [comment]
I'm glad it works now! If it re-appears, feel free to re-open the issue. Thanks!
