### ISSUE TITLE
Move Up / Down Is Not Inverse

### ISSUE THREAD

**Issue by hediet** [p42ai/refactor-vscode#43]
![recording](https://user-images.githubusercontent.com/2931520/182885697-afb740ba-86b7-41d1-9f10-640a8267ae67.gif)

**Comment by lgrammel** [comment]
This looks like a whitespace issue, or am I missing something? (just confirming that I understand this correctly)

**Comment by hediet** [comment]
Yes, there is more and more whitespace.

**Comment by lgrammel** [comment]
I've just released `v1.133.1` which resolves this issue. Please re-open the bug if you still encounter it. Thanks for reporting!
