### ISSUE TITLE
Smart extend keyboard short cut conflicts with default Move Line Up/Move Line Down

### ISSUE THREAD

**Issue by gregveres** [p42ai/refactor-vscode#47]
I am not sure if you noticed, but by default, Move Line Up is bound to Alt + UpArrow and Move Line Down is bound to Alt + DownArrow.

Given how incredibly useful Move Line Up/Down are, I would expect that everyone would be complaining that p42 just installed a conflicting set of keyboard bindings. 

I am removing the bindings that p42 added. I am sure there is a better set of keys to bind the smart expand to.

**Comment by lgrammel** [comment]
@gregveres thanks for the bug report! I agree, this should not happen - will put out a fix soon.

**Comment by lgrammel** [comment]
I've released `v1.142.2`, which removes the smart selection keybindings. Thanks again for the bug report!
