### ISSUE TITLE
Support Moving Up / Down Multiple Items At Once

### ISSUE THREAD

**Issue by hediet** [p42ai/refactor-vscode#49]
E.g. when all this is selected and I press control+down:

![image](https://user-images.githubusercontent.com/2931520/187167639-8e02d2ac-1e71-4325-8538-0c2eb5de8a64.png)

**Comment by lgrammel** [comment]
Thanks, this is a great suggestion!

**Comment by lgrammel** [comment]
I've added this feature for most move statements in `v1.147.0`. When there is a selection that spans several elements (can be partial) and move gets started, it moves multiple code elements.
