### ISSUE TITLE
Showing wrong hint for inline-return

### ISSUE THREAD

**Issue by chandan192** [p42ai/refactor-vscode#5]
Original code:

        public replaceVariables(path: Path, variables: { [key: string]: string }) {
            const me = this;
            let newPath;

            newPath = me.resolvePath(path);

            Object.keys(variables).forEach((variable: string) => {
                newPath.replace('{' + variable + '}', variables[variable]);
            });

            return newPath;
        }

![Screenshot 2021-11-10 133109](https://user-images.githubusercontent.com/36302444/141073503-2d8fa764-08c6-4258-9cc0-e884403a5db0.png)

code after the fix:

        public replaceVariables(path: Path, variables: { [key: string]: string }) {
            const me = this;
            let newPath;

            return me.resolvePath(path);

            //unreachable code after fix
            Object.keys(variables).forEach((variable: string) => {
                newPath.replace('{' + variable + '}', variables[variable]);
            });

        }

![c](https://user-images.githubusercontent.com/36302444/141074079-36d1539a-974b-409d-9b4f-ad668465b4ea.png)

**Comment by lgrammel** [comment]
Thanks for the detailed bug report! I'll update once I have a fix.

**Comment by lgrammel** [comment]
@chandan192 I just released version 1.50.5, which fixes the bug. Please re-open this issue if you still encounter the bug 1.50.5 or higher. Thanks again for the bug report!
