### ISSUE TITLE
To Arrow Anchor Point

### ISSUE THREAD

**Issue by hediet** [p42ai/refactor-vscode#51]
![image](https://user-images.githubusercontent.com/2931520/187940127-c73d3528-c604-4638-84f7-601bc17f94f8.png)

Wasn't the "Remove {...} from arrow function" action suggested here once?

**Comment by lgrammel** [comment]
Thanks, I'll take a look!

**Comment by lgrammel** [comment]
It is available as a regular code action (convert), but not as a quickfix at that position. Were you expecting a quickfix (I could increase the quickfix range)?

**Comment by hediet** [comment]
Yep, was expecting a quick fix there

**Comment by lgrammel** [comment]
Cool, will change it in the next update. Btw, if you want to add/remove braces even faster, you can try the `toggle braces` shortcut (`Ctrl + Alt + B` on Windows).

**Comment by hediet** [comment]
I already use quite a few shortcuts and would be happy if I could remember the one for organize imports...

**Comment by lgrammel** [comment]
I have trouble with that one as well for some reason.

"Remove braces from arrow function" is available as quick fix on the "return" keyword starting with `v1.147.1` - thanks for the suggestion!
