### ISSUE TITLE
`You can remove the IIFE` is unsafe

### ISSUE THREAD

**Issue by AlexXanderGrib** [p42ai/refactor-vscode#52]
Code:
```javascript
function tick() { /* works with canvas */ }

(function loop() {
  tick();
  requestAnimationFrame(loop);
})();
```

p42 suggests to remove IIFE and deems it safe. Result:

```javascript
{
  tick();
  requestAnimationFrame(loop); // So loop is undefined
}
```

**Comment by lgrammel** [comment]
Thanks for the bug report!

Starting in `v1.147.2`, remove IIFE is not available any more when there are self-references to the function. Please re-open if the bug still occurs.
