### ISSUE TITLE
convert to const in for-of loops

### ISSUE THREAD

**Issue by j4k0xb** [p42ai/refactor-vscode#54]
should also work for
```js
for (let item of array) {
  console.log(item);
}
```
->
```js
for (const item of array) {
  console.log(item);
}
```

**Comment by lgrammel** [comment]
@j4k0xb Thanks for the bug report! I've just released `v1.150.3`, which fixes this bug. Please re-open this issue if you still encounter the issue in `v1.150.3` or higher.
