### ISSUE TITLE
Convert if-else to conditional expression does not works with this.var

### ISSUE THREAD

**Issue by chandan192** [p42ai/refactor-vscode#7]
`let x;
    if (me.isEnabledColumnFilter === true) {
     x = 'Disable Filters';
    } else {
      x = 'Enable Filters';
    }`

Here, refactoring works perfectly and yield result is 

` let x;
    x = me.isEnabledColumnFilter === true ? 'Disable Filters' : 'Enable Filters';`

But, the linting is not shown with **this** keyword. Below is the code.

`if (this.isEnabledColumnFilter === true) {
      this.filterTitle = 'Disable Filters';
    } else {
      this.filterTitle = 'Enable Filters';
    }`

**Comment by lgrammel** [comment]
Thanks for the suggestion!

I will see if I can integrate it in one of the next releases.

**Comment by lgrammel** [comment]
The feature is implemented and will be included in the next release.

**Comment by lgrammel** [comment]
@chandan192 I've just released version 1.57.0, which supports your suggested improvement. Please re-open if you still cannot run the refactoring on version 1.57.0 or higher. Thanks for the suggestion!

**Comment by chandan192** [comment]
Hi @lgrammel, 
converting if-else to conditional expression is not working for the below case.

![image](https://user-images.githubusercontent.com/36302444/147469870-12058e3c-7270-4ff2-b232-62e7c2041819.png)

**Comment by lgrammel** [comment]
Hi @chandan192 - thanks for the bug report. I'll look into it.

**Comment by lgrammel** [comment]
Fixed in 1.64.2 - thanks for the bug report!
