### ISSUE TITLE
Support to convert if-else if to switch case.

### ISSUE THREAD

**Issue by chandan192** [p42ai/refactor-vscode#8]
Can we have an option to convert if else if to switch case? 

I am using tslint but it only shows the linting but does not refactors it.

**Comment by lgrammel** [comment]
Thanks, great idea! Converting if-else to switch has been on my list for a while. Do you have a reference to the lint rule? The conversion only makes sense in certain cases.

**Comment by chandan192** [comment]
![image](https://user-images.githubusercontent.com/36302444/146670521-2d288d9a-c28f-4799-a575-c5f6e70d3bde.png)

Please see this image for reference.

**Comment by lgrammel** [comment]
@chandan192 I've just released version 1.61, which supports converting if-else to switch. Thanks for the suggestion!

**Comment by chandan192** [comment]
Hi @lgrammel, 
converting if-else to switch case does not work for the inlined variables.

Please see the snap below for reference.
![image](https://user-images.githubusercontent.com/36302444/147467924-58650186-aac2-4610-bffc-6b8b46cc285a.png)

**Comment by chandan192** [comment]
Hi @lgrammel, 
Hope you are doing well.

refactoring if-else to switch case doesn't work for if condition with && or || operation.

![image](https://user-images.githubusercontent.com/36302444/147469477-be92f4ab-c16d-4f91-adf6-c48b71a3420a.png)

**Comment by lgrammel** [comment]
@chandan192 thanks for the bug report. I'll look into adding support for `||`. It is not clear to me how to translate `&&` into a switch, do you have an example?

**Comment by chandan192** [comment]
@lgrammel, you are right, I didn't think of the condition with **&&**. But we can have support for **||**.

**Comment by lgrammel** [comment]
Fixed in 1.64.2 - thanks for the bug report!
