### ISSUE TITLE
convert-to-for-of-loop / convert-to-foreach-loop linting and refactoring not working.

### ISSUE THREAD

**Issue by chandan192** [p42ai/refactor-vscode#9]
Hi @lgrammel, 
Linting for convert-to-for-of-loop / convert-to-foreach-loop is not showing. Also, no refactoring option is available for to convert simple for loop to for-of loop.

![image](https://user-images.githubusercontent.com/36302444/146812318-c71d329c-161b-4c31-9820-30058615c7d3.png)

**Comment by lgrammel** [comment]
Hi @chandan192 - thanks for the bug report. I was able to reproduce the issue and will look into a fix.

**Comment by lgrammel** [comment]
This is because `record[i]` is inlined. If you extract it into its own variable, the refactoring will become available. I'll look into extending the refactoring, so that the extraction is not necessary.

**Comment by lgrammel** [comment]
Hey @chandan192 - I finally got around to implementing your idea. It is available in version `1.71.0` and higher. Thanks for the suggestion!
